### PR TITLE
Hotfix - Select Element Refactoring

### LINKED ISSUE #21: [hotifx] Drop-Down on Windows
### :fire: Describe the bug
On Windows, the drop-down field is apparently not rendered correctly (empty entries).

### :mag: To Reproduce [if necessary]
Steps to reproduce the behavior [on Windows]:
1. Go to the interface for creating a new resource type.
2. Fill the form until you can add new attributes.
3. Try to change the type of a new attribute.
4. :tada: The list might only show a single entry, instead of the whole list of possible data types.

### PR DESCRIPTION
**Pull request by friedow**
This fixes #21.

### CODE REVIEW

File: src/components/Select.vue [hunk 1]
```diff
@@ -29,8 +43,20 @@ export default class Select extends Vue {
...
+
   @Prop(Boolean)
   public required?: boolean;
+
+  @Prop(Array)
+  public options!: Option[];
+
+  public optionsVisible: boolean = false;
+
+  get selectedOption(): Option {
```
Comment (MaximilianV) [inline src/components/Select.vue:57]: Why is only the currently selected value stored and not `Option` object as a whole?
Wouldn't it be easier?

File: src/views/CreateType.vue [hunk 2]
```diff
@@ -167,6 +164,23 @@ export default class Types extends Mixins(Translate) {
       },
     };
   }
+
+  public get dataTypeOptions(): Option[] {
```
Comment (MaximilianV) [inline src/views/CreateType.vue:169]: I think we should move the list of available data types to the `utils` or even an extra file!
I'm sure we'll add more data types later and it would be nice to have the definition at one place and not somewhere in a view :crystal_ball:

File: src/views/Resources.vue [hunk 3]
```diff
@@ -2,15 +2,7 @@
...
-      <Select :value.sync="selectedType" name="Resource Type">
-        <option value="">All Resource Types</option>
-        <option
-          :key="resourceType.id"
-          :value="resourceType.name"
-          v-for="resourceType in nonAbstractResourceTypes">
-          {{resourceType.name}}
-        </option>
-      </Select>
+      <Select :value.sync="selectedType" placeholder="All Resource Types" name="Resource Type" :options="nonAbstractResourceTypes" />
```
Comment (MaximilianV) [inline src/views/Resources.vue]: This lines seems to be quite long :dromedary_camel:

**Review by MaximilianV — CHANGES_REQUESTED** [review]

**Comment by MaximilianV** [comment]
:point_up_2: I'd like to have a link indicating mouse cursor when hovering over select entries!
And on the select box itself, too!

File: src/components/Select.vue (hunk 1 above)
Comment (friedow) [reply src/components/Select.vue:57]: This is similar to the html select element which also returns only the value of the currently selected option.

File: src/views/CreateType.vue (hunk 2 above)
Comment (friedow) [reply src/views/CreateType.vue:169]: done

File: src/views/Resources.vue (hunk 3 above)
Comment (friedow) [reply src/views/Resources.vue]: done

**Review by MaximilianV — DISMISSED** [review]
:+1:

**Review by MaximilianV — APPROVED** [review]
